# Generated by Django 5.1 on 2024-08-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_hash_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='hash_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Hashed ID'),
        ),
    ]
